// ATTACK-Navi - Copyright (c) 2026 TeamStarWolf
// https://github.com/TeamStarWolf/ATTACK-Navi - MIT License
import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { BehaviorSubject, Observable, shareReplay, map, catchError, of } from 'rxjs';

export type AssetType = 'tool' | 'channel' | 'x-account' | 'book' | 'field-note';

export interface LibraryAsset {
  id: string;
  type: AssetType;
  title: string;
  url: string;
  description: string;
  category: string;
  subcategory: string;
  vendor: string;
  handle: string;
  affiliation: string;
  attack_tactics: string[];
  metadata: Record<string, unknown>;
}

export interface LibraryData {
  generated_at: string;
  counts: Partial<Record<AssetType, number>>;
  categories: Partial<Record<AssetType, string[]>>;
  vendors: Record<string, number>;
  tactic_counts: Record<string, number>;
  assets: LibraryAsset[];
}

const EMPTY: LibraryData = {
  generated_at: '',
  counts: {},
  categories: {},
  vendors: {},
  tactic_counts: {},
  assets: [],
};

/** Canonical ATT&CK tactic ordering for UI display. */
export const ATTACK_TACTIC_ORDER: string[] = [
  'reconnaissance', 'resource-development', 'initial-access', 'execution',
  'persistence', 'privilege-escalation', 'defense-evasion', 'credential-access',
  'discovery', 'lateral-movement', 'collection', 'command-and-control',
  'exfiltration', 'impact',
];

export function tacticLabel(slug: string): string {
  // "credential-access" -> "Credential Access"
  return slug.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
}

/**
 * Loads and caches the unified library index (tools / channels / X accounts / books).
 * Source: src/assets/library.json — generated by build_library_index.py in the
 * profile repo. Re-run the builder + copy to refresh.
 */
@Injectable({ providedIn: 'root' })
export class LibraryService {
  private http = inject(HttpClient);
  private loaded = new BehaviorSubject<boolean>(false);

  /** Hot observable that emits the library data once loaded. */
  readonly library$: Observable<LibraryData> = this.http
    .get<LibraryData>('assets/library.json')
    .pipe(
      map(data => {
        this.loaded.next(true);
        return data;
      }),
      catchError(err => {
        console.warn('[LibraryService] failed to load library.json', err);
        this.loaded.next(true);
        return of(EMPTY);
      }),
      shareReplay(1),
    );

  loaded$: Observable<boolean> = this.loaded.asObservable();
}
