// ATTACK-Navi - Copyright (c) 2026 TeamStarWolf
// https://github.com/TeamStarWolf/ATTACK-Navi - MIT License
import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { BehaviorSubject, Observable, shareReplay, map, catchError, of } from 'rxjs';
import { ENTERPRISE_TACTIC_ORDER, tacticAliases, tacticLabel } from './attack-tactics';

export type AssetType = 'tool' | 'channel' | 'x-account' | 'book' | 'field-note';

export interface LibraryAsset {
  id: string;
  type: AssetType;
  title: string;
  url: string;
  description: string;
  category: string;
  subcategory: string;
  vendor: string;
  handle: string;
  affiliation: string;
  // Optional: parsed from JSON where the field may be absent (the service and
  // templates guard with ?./??). Typed honestly so those guards are valid.
  attack_tactics?: string[];
  metadata: Record<string, unknown>;
}

export interface LibraryData {
  generated_at: string;
  counts: Partial<Record<AssetType, number>>;
  categories: Partial<Record<AssetType, string[]>>;
  vendors: Record<string, number>;
  tactic_counts: Record<string, number>;
  assets: LibraryAsset[];
}

const EMPTY: LibraryData = {
  generated_at: '',
  counts: {},
  categories: {},
  vendors: {},
  tactic_counts: {},
  assets: [],
};

/** Canonical (Enterprise v19) ATT&CK tactic ordering for UI display. */
export const ATTACK_TACTIC_ORDER: string[] = [...ENTERPRISE_TACTIC_ORDER];

export { tacticLabel };

/** True when an asset's tactic tags cover `slug` directly or through an alias. */
export function assetMatchesTactic(asset: Pick<LibraryAsset, 'attack_tactics'>, slug: string): boolean {
  const tags = asset.attack_tactics;
  if (!tags || tags.length === 0) return false;
  return tacticAliases(slug).some(s => tags.includes(s));
}

/**
 * library.json is produced by an external generator that still tags assets
 * with the pre-v19 `defense-evasion` slug. Fill in counts for every current
 * tactic that the generator did not emit, counting assets through the alias
 * map, so the Coverage tab and tactic chips reflect the v19 matrix without
 * waiting for the generator to catch up.
 */
export function normalizeLibraryData(data: LibraryData): LibraryData {
  const assets = data.assets ?? [];
  const tactic_counts: Record<string, number> = { ...(data.tactic_counts ?? {}) };
  for (const slug of ENTERPRISE_TACTIC_ORDER) {
    if (tactic_counts[slug] !== undefined) continue;
    tactic_counts[slug] = assets.filter(a => assetMatchesTactic(a, slug)).length;
  }
  return { ...data, assets, tactic_counts };
}

/**
 * Loads and caches the unified library index (tools / channels / X accounts / books).
 * Source: src/assets/library.json — generated by build_library_index.py in the
 * profile repo. Re-run the builder + copy to refresh.
 */
@Injectable({ providedIn: 'root' })
export class LibraryService {
  private http = inject(HttpClient);
  private loaded = new BehaviorSubject<boolean>(false);
  private cached: LibraryData = EMPTY;

  /** Hot observable that emits the library data once loaded. */
  readonly library$: Observable<LibraryData> = this.http
    .get<LibraryData>('assets/library.json')
    .pipe(
      map(raw => {
        const data = normalizeLibraryData(raw);
        this.loaded.next(true);
        this.cached = data;
        return data;
      }),
      catchError(err => {
        console.warn('[LibraryService] failed to load library.json', err);
        this.loaded.next(true);
        return of(EMPTY);
      }),
      shareReplay(1),
    );

  loaded$: Observable<boolean> = this.loaded.asObservable();

  constructor() {
    // Eager-subscribe so cross-reference helpers work even when the Library
    // view hasn't been opened yet (e.g. when used by the technique sidebar
    // in the ATT&CK Workbench).
    this.library$.subscribe();
  }

  // ─── Cross-reference helpers ───────────────────────────────────────────────
  // Used by ATT&CK Workbench panels to surface Library assets relevant to a
  // selected technique, tactic, or freeform query.

  /**
   * All assets tagged with the given ATT&CK tactic slug. Resolves through
   * tactic aliases so a v19 `stealth` lookup finds assets the generator
   * tagged `defense-evasion`, and vice versa for the Mobile bundle.
   */
  getAssetsForTactic(slug: string): LibraryAsset[] {
    if (!slug) return [];
    return this.cached.assets.filter(a => assetMatchesTactic(a, slug));
  }

  /**
   * Loose match of an asset against a technique's ID, name, or related text.
   * Used by the technique sidebar to suggest related Library assets.
   */
  getAssetsForTechnique(attackId: string, name: string, tacticSlugs: string[]): LibraryAsset[] {
    const idLower = (attackId ?? '').toLowerCase().trim();
    const nameLower = (name ?? '').toLowerCase().trim();
    // Expand through aliases so v19 technique tactics match legacy asset tags.
    const tactics = new Set((tacticSlugs ?? []).flatMap(s => tacticAliases(s)));

    // No signal to score against → return empty
    if (!idLower && !nameLower && tactics.size === 0) return [];

    // Score assets: tactic-tag match = 2, name keyword match = 3, attack-id mention = 5
    const scored: Array<{ asset: LibraryAsset; score: number }> = [];

    for (const a of this.cached.assets) {
      let score = 0;
      const haystack = `${a.title} ${a.description} ${a.category} ${a.subcategory}`.toLowerCase();

      if (tactics.size > 0 && a.attack_tactics?.some(t => tactics.has(t))) score += 2;

      if (idLower && haystack.includes(idLower)) score += 5;

      if (nameLower) {
        // Match meaningful keyword substrings of the technique name (drop short tokens).
        const tokens = nameLower.split(/[\s\W]+/).filter(t => t.length >= 5);
        for (const tok of tokens) {
          if (haystack.includes(tok)) score += 3;
        }
      }

      if (score > 0) scored.push({ asset: a, score });
    }

    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, 24).map(s => s.asset);
  }
}
