// ATTACK-Navi - Copyright (c) 2026 TeamStarWolf
// https://github.com/TeamStarWolf/ATTACK-Navi - MIT License
import { Injectable } from '@angular/core';
import { Domain } from '../models/domain';
import { Technique } from '../models/technique';
import { ImplStatus } from './implementation.service';
import { HeatmapMode } from './filter.service';

@Injectable({ providedIn: 'root' })
export class MatrixExportService {

  exportPng(domain: Domain, implStatusMap: Map<string, ImplStatus>, heatmapMode: HeatmapMode): void {
    const CELL_W = 140;
    const CELL_H = 22;
    const GAP = 6;
    const HEADER_H = 32;
    const PADDING = 14;
    const FOOTER_H = 28;
    const CELL_GAP = 2; // vertical gap between cells
    const DPR = 2; // device pixel ratio for retina quality

    const cols = domain.tacticColumns;

    // Only parent techniques per tactic column
    const parentCols = cols.map(col => ({
      tactic: col.tactic,
      techniques: col.techniques.filter(t => !t.isSubtechnique),
    }));

    const maxRows = Math.max(...parentCols.map(c => c.techniques.length), 0);

    const logicalW = parentCols.length * (CELL_W + GAP) - GAP + PADDING * 2;
    const logicalH = HEADER_H + maxRows * (CELL_H + CELL_GAP) + FOOTER_H + PADDING * 2;

    const canvas = document.createElement('canvas');
    canvas.width = logicalW * DPR;
    canvas.height = logicalH * DPR;

    const ctx = canvas.getContext('2d')!;
    ctx.scale(DPR, DPR);

    // Background
    ctx.fillStyle = '#070d14';
    ctx.fillRect(0, 0, logicalW, logicalH);

    // Draw each tactic column
    parentCols.forEach((col, colIdx) => {
      const colX = PADDING + colIdx * (CELL_W + GAP);
      const headerY = PADDING;

      // Tactic header
      ctx.fillStyle = '#0d1f2d';
      this.roundRect(ctx, colX, headerY, CELL_W, HEADER_H, 4);
      ctx.fill();

      // Header border accent (top line)
      ctx.fillStyle = '#58a6ff';
      ctx.fillRect(colX, headerY, CELL_W, 2);

      // Tactic name
      ctx.fillStyle = '#58a6ff';
      ctx.font = 'bold 11px sans-serif';
      ctx.textBaseline = 'middle';
      ctx.textAlign = 'center';
      const tacticLabel = this.truncate(col.tactic.name, 20);
      ctx.fillText(tacticLabel, colX + CELL_W / 2, headerY + HEADER_H / 2);

      // Technique cells
      col.techniques.forEach((tech, rowIdx) => {
        const cellX = colX;
        const cellY = PADDING + HEADER_H + CELL_GAP + rowIdx * (CELL_H + CELL_GAP);

        const bgColor = this.getCellColor(tech, domain, implStatusMap, heatmapMode);

        // Cell background
        ctx.fillStyle = bgColor;
        this.roundRect(ctx, cellX, cellY, CELL_W, CELL_H, 3);
        ctx.fill();

        // Technique ID (small, dimmer)
        ctx.fillStyle = 'rgba(255,255,255,0.55)';
        ctx.font = '9px sans-serif';
        ctx.textAlign = 'right';
        ctx.textBaseline = 'top';
        ctx.fillText(tech.attackId, cellX + CELL_W - 4, cellY + 3);

        // Technique name
        ctx.fillStyle = '#ffffff';
        ctx.font = '10px sans-serif';
        ctx.textAlign = 'left';
        ctx.textBaseline = 'middle';
        const nameLabel = this.truncate(tech.name, 17);
        ctx.fillText(nameLabel, cellX + 4, cellY + CELL_H / 2 + 1);
      });
    });

    // Footer text
    const footerY = PADDING + HEADER_H + maxRows * (CELL_H + CELL_GAP) + CELL_GAP + 8;
    ctx.fillStyle = 'rgba(255,255,255,0.3)';
    ctx.font = '10px sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(
      `Generated by MITRE ATT&CK Navi  •  ATT&CK v${domain.attackVersion}  •  ${new Date().toISOString().slice(0, 10)}`,
      logicalW / 2,
      footerY + FOOTER_H / 2,
    );

    // Trigger download
    canvas.toBlob(blob => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'attack-matrix.png';
      a.click();
      URL.revokeObjectURL(url);
    }, 'image/png');
  }

  private getCellColor(
    tech: Technique,
    domain: Domain,
    implStatusMap: Map<string, ImplStatus>,
    heatmapMode: HeatmapMode,
  ): string {
    if (heatmapMode === 'status') {
      // Determine "best" implementation status across all mitigations for this technique
      const rels = domain.mitigationsByTechnique.get(tech.id) ?? [];
      const STATUS_ORDER: ImplStatus[] = ['implemented', 'in-progress', 'planned', 'not-started'];
      let bestStatus: ImplStatus | null = null;
      for (const rel of rels) {
        const s = implStatusMap.get(rel.mitigation.id);
        if (!s) continue;
        const idx = STATUS_ORDER.indexOf(s);
        const bestIdx = bestStatus ? STATUS_ORDER.indexOf(bestStatus) : Infinity;
        if (idx < bestIdx) bestStatus = s;
      }
      if (bestStatus === 'implemented') return '#1b5e20';
      if (bestStatus === 'in-progress') return '#1565c0';
      if (bestStatus === 'planned') return '#4a148c';
      if (bestStatus === 'not-started') return '#424242';
      return '#1c2a38';
    }

    // Coverage mode (and default for all other modes)
    const count = tech.mitigationCount;
    if (count === 0) return '#4a1010';
    if (count === 1) return '#7a2a00';
    if (count === 2) return '#7a5a00';
    if (count === 3) return '#2e5a1a';
    return '#1b5e20';
  }

  /** Simulate canvas ellipsis by truncating at maxChars */
  private truncate(text: string, maxChars: number): string {
    if (text.length <= maxChars) return text;
    return text.slice(0, maxChars - 1) + '\u2026';
  }

  /** Helper to draw a rounded rectangle path */
  private roundRect(
    ctx: CanvasRenderingContext2D,
    x: number, y: number, w: number, h: number, r: number,
  ): void {
    if (ctx.roundRect) {
      ctx.beginPath();
      ctx.roundRect(x, y, w, h, r);
    } else {
      // Fallback for environments without roundRect
      ctx.beginPath();
      ctx.moveTo(x + r, y);
      ctx.lineTo(x + w - r, y);
      ctx.quadraticCurveTo(x + w, y, x + w, y + r);
      ctx.lineTo(x + w, y + h - r);
      ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
      ctx.lineTo(x + r, y + h);
      ctx.quadraticCurveTo(x, y + h, x, y + h - r);
      ctx.lineTo(x, y + r);
      ctx.quadraticCurveTo(x, y, x + r, y);
      ctx.closePath();
    }
  }
}
